apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-feed
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
    