apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reverseproxy
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
    